version: "3.9"
services:
#  build:
#    build:
#      context: ./.docker/build
#    volumes:
#      - ".:/app"
#    environment:
#      NODE_ENV: development
#    working_dir: /app

  local:
    build:
      context: ./.docker/local
    ports:
      - "8083:8083"
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    networks:
      - backend
    command: /app/run.sh
#    depends_on:
#      - "build"

networks:
  backend:
    external: true
    name: keycloak_network
    