version: "3.9"
services:
  frontend:
    build:
      context: ./
    ports:
      - "8085:80"
    environment:
      NODE_ENV: development
    working_dir: /app

  local:
    build:
      context: ./.docker/local
    ports:
      - "8083:8083"
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    networks:
      - montana
    command: /app/run.sh
#    depends_on:
#      - "build"

networks:
  montana:
    external: true
    name: montana_network