version: "3.9"
services:
  web:
    build:
      context: ./
      #args:
    ports:
      - "8083:80"
 #   volumes:
 #     - ".:/app"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    networks:
      - backend

networks:
  backend:
    external: true
    name: keycloak_network
    