version: "3.9"
services:
  web:
    image: node:15.8-alpine3.11
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    command: sh -c "cd /app; npm install; npm run serve"